/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CrossChainTransfer__factory } from "./CrossChainTransfer__factory";
export { ITRC20__factory } from "./ITRC20__factory";
