/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CrossChainTransfer } from "./CrossChainTransfer";
export type { ITRC20 } from "./ITRC20";
export * as factories from "./factories";
export { CrossChainTransfer__factory } from "./factories/CrossChainTransfer__factory";
export { ITRC20__factory } from "./factories/ITRC20__factory";
